Repository composer/composer, pull requests merged in 2019-01, with the labels that each got.

#7909 Add alias of run-script command
  src/Composer/Command/RunScriptCommand.php
Labels: Feature

#7912 Feature/no api config
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/ConfigCommand.php
  src/Composer/Config.php
  src/Composer/Repository/Vcs/GitHubDriver.php
Labels: Feature, Needs Work

#7937 Fix defaultRepos fallback does not use auth config
  src/Composer/Repository/RepositoryFactory.php
Labels: Bug
