Repository composer/composer, pull requests merged in 2020-02, with the labels that each got.

#8562 Uses config data from Composer object whenever possible on ArchiveCommand
  .php_cs
  src/Composer/Command/ArchiveCommand.php
  tests/Composer/Test/Command/ArchiveCommandTest.php
Labels: Bug

#8575 Added test for exclude-from-classmap (see issue #8563)
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
Labels: Bug

#8566 Restore installer events and add a PRE_POOL_CREATE hook for plugins
  doc/articles/scripts.md
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Installer.php
  src/Composer/Installer/InstallerEvent.php
  src/Composer/Installer/InstallerEvents.php
  src/Composer/Plugin/PluginEvents.php
  src/Composer/Plugin/PrePoolCreateEvent.php
  src/Composer/Repository/RepositorySet.php
  tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
  tests/Composer/Test/Installer/InstallerEventTest.php
Labels: Feature, Refactoring

#8453 Add funding field to composer.json and composer fund command
  doc/03-cli.md
  doc/04-schema.md
  res/composer-schema.json
  src/Composer/Command/FundCommand.php
  src/Composer/Console/Application.php
  src/Composer/Installer.php
  src/Composer/Package/AliasPackage.php
  src/Composer/Package/CompletePackage.php
  src/Composer/Package/CompletePackageInterface.php
  src/Composer/Package/Dumper/ArrayDumper.php
  src/Composer/Package/Loader/ArrayLoader.php
  src/Composer/Package/Loader/ValidatingArrayLoader.php
  src/Composer/Repository/Vcs/GitHubDriver.php
  tests/Composer/Test/Fixtures/installer/install-funding-notice.test
  tests/Composer/Test/Json/Fixtures/composer.json
  tests/Composer/Test/Package/Dumper/ArrayDumperTest.php
  tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
  tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
Labels: Feature
