Repository composer/composer, pull requests merged in 2020-10, with the labels that each got.

#9270 Version Guesser: Look at branches on remotes origin & upstream to look for version numbers too
  src/Composer/Package/Version/VersionGuesser.php
  tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php
  tests/Composer/Test/Package/Version/VersionGuesserTest.php
Labels: Bug

#9257 With-dependencies alias
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
Labels: Feature

#9212 Specify APCu autoloader prefix
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Installer.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
Labels: Feature

#9223 Partial updates should remove all unused dependencies
  src/Composer/DependencyResolver/LockTransaction.php
  src/Composer/DependencyResolver/Pool.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/Request.php
  src/Composer/DependencyResolver/Rule.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/Installer.php
  tests/Composer/Test/Fixtures/installer/alias-solver-problems2.test
  tests/Composer/Test/Fixtures/installer/partial-update-from-lock.test
  tests/Composer/Test/Fixtures/installer/remove-deletes-unused-deps.test
  tests/Composer/Test/Fixtures/installer/remove-does-nothing-if-removal-requires-update-of-dep.test
  tests/Composer/Test/Fixtures/installer/root-alias-change-with-circular-dep.test
  tests/Composer/Test/Fixtures/installer/update-allow-list-require-new-replace.test
  tests/Composer/Test/Fixtures/installer/update-allow-list-with-dependencies-require-new-replace-mutual.test
Labels: Feature

#9312 Solver: Prevent infinite recursion in analyzeUnsolvableRule
  src/Composer/DependencyResolver/Solver.php
  tests/Composer/Test/Fixtures/installer/github-issues-7051.test
  tests/Composer/Test/Fixtures/installer/github-issues-9012.test
  tests/Composer/Test/Fixtures/installer/provider-conflicts3.test
Labels: Bug, Solver

#8733 Test for issue resulting in overly long learnt rules and solver bug exception
  tests/Composer/Test/Fixtures/installer-slow/github-issues-7665.test
  tests/Composer/Test/InstallerTest.php
Labels: Bug

#9158 Fix symlink check
  src/Composer/Package/Archiver/ArchivableFilesFinder.php
Labels: Bug, Needs Work

#9326 Docs: Remove unnecessary uses of simple/easy
  doc/00-intro.md
  doc/01-basic-usage.md
  doc/02-libraries.md
  doc/03-cli.md
  doc/04-schema.md
  doc/05-repositories.md
  doc/06-config.md
  doc/articles/autoloader-optimization.md
  doc/articles/custom-installers.md
  doc/articles/handling-private-packages-with-satis.md
  doc/articles/scripts.md
  doc/articles/versions.md
  doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md
  doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
  doc/faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md
  doc/fixtures/fixtures.md
Labels: Documentation

#9323 Fix support of provided packages in the why-not command
  src/Composer/Repository/BaseRepository.php
Labels: Bug

#9339 Fix plugin install order for plugins modifying downloads
  src/Composer/DependencyResolver/Transaction.php
  src/Composer/Installer/InstallationManager.php
  tests/Composer/Test/DependencyResolver/TransactionTest.php
Labels: Bug
