Repository composer/composer, pull requests merged in 2020-01, with the labels that each got.

#8520 Implemented way to add packages into suggest through CLI
  src/Composer/Command/ConfigCommand.php
  src/Composer/Json/JsonManipulator.php
  tests/Composer/Test/Json/JsonManipulatorTest.php
Labels: Feature

#8372 Hide installed packages from suggestions when package is not found
  src/Composer/Command/InitCommand.php
Labels: Feature

#8331 8330 Correct issue where permission umask of files were not set when …
  src/Composer/Package/Archiver/ZipArchiver.php
Labels: Feature

#8533 Remove callback and pass stabilities all the way instead
  src/Composer/DependencyResolver/Pool.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/Request.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/Installer.php
  src/Composer/Package/Version/StabilityFilter.php
  src/Composer/Repository/ArrayRepository.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Repository/CompositeRepository.php
  src/Composer/Repository/RepositoryInterface.php
  src/Composer/Repository/RepositorySet.php
  tests/Composer/Test/DependencyResolver/PoolTest.php
  tests/Composer/Test/DependencyResolver/RequestTest.php
  tests/Composer/Test/DependencyResolver/RuleSetTest.php
  tests/Composer/Test/DependencyResolver/RuleTest.php
  tests/Composer/Test/DependencyResolver/SolverTest.php
  tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test
Labels: Refactoring

#8538 Append the bin dir on each listener iteration
  src/Composer/EventDispatcher/EventDispatcher.php
  tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
Labels: Bug

#8529 Change only modified files for docker caching
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Installer.php
  src/Composer/Json/JsonFile.php
Labels: Bug

#8545 Add support for "composer show --format=json <package>" #8544
  src/Composer/Command/ShowCommand.php
Labels: Feature

#8561 Allow providers which are selected to be installed in place of existing packages which do not satisfy requirements
  src/Composer/DependencyResolver/Pool.php
  tests/Composer/Test/Fixtures/installer/provider-packages-can-be-installed-if-selected.test
  tests/Composer/Test/Fixtures/installer/provider-packages-can-be-installed-together-with-provided-if-both-installable.json
  tests/Composer/Test/Fixtures/installer/provider-packages-can-not-be-installed-unless-selected.test
Labels: Feature

#8558 Improve error reporting of solver issues
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/Rule.php
  src/Composer/DependencyResolver/RuleSet.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/DependencyResolver/SolverProblemsException.php
  src/Composer/Downloader/GitDownloader.php
  src/Composer/Installer.php
  src/Composer/Plugin/PluginManager.php
  src/Composer/Repository/ArrayRepository.php
  src/Composer/Repository/ArtifactRepository.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Repository/CompositeRepository.php
  src/Composer/Repository/InstalledArrayRepository.php
  src/Composer/Repository/InstalledFilesystemRepository.php
  src/Composer/Repository/LockArrayRepository.php
  src/Composer/Repository/PackageRepository.php
  src/Composer/Repository/PathRepository.php
  src/Composer/Repository/PearRepository.php
  src/Composer/Repository/PlatformRepository.php
  src/Composer/Repository/RepositoryInterface.php
  src/Composer/Repository/RepositorySet.php
  src/Composer/Repository/RootPackageRepository.php
  src/Composer/Repository/VcsRepository.php
  src/Composer/Util/AuthHelper.php
  src/Composer/Util/Git.php
  src/Composer/Util/Hg.php
  src/Composer/Util/Http/CurlDownloader.php
  src/Composer/Util/RemoteFilesystem.php
  src/Composer/Util/Url.php
  tests/Composer/Test/DependencyResolver/RuleSetTest.php
  tests/Composer/Test/DependencyResolver/RuleTest.php
  tests/Composer/Test/DependencyResolver/SolverTest.php
  tests/Composer/Test/Fixtures/installer/broken-deps-do-not-replace.test
  tests/Composer/Test/Fixtures/installer/conflict-between-dependents.test
  tests/Composer/Test/Fixtures/installer/conflict-between-root-and-dependent.test
  tests/Composer/Test/Fixtures/installer/github-issues-4319.test
  tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test
  tests/Composer/Test/Fixtures/installer/provider-conflicts.test
  tests/Composer/Test/Fixtures/installer/provider-conflicts2.test
  tests/Composer/Test/Fixtures/installer/provider-conflicts3.test
  tests/Composer/Test/Fixtures/installer/provider-packages-can-not-be-installed-unless-selected.test
  tests/Composer/Test/Fixtures/installer/repositories-priorities.test
  tests/Composer/Test/Fixtures/installer/solver-problems.test
  tests/Composer/Test/InstallerTest.php
  tests/Composer/Test/Util/UrlTest.php
Labels: Feature
