Repository composer/composer, pull requests merged in 2020-06, with the labels that each got.

#8916 Ensure loading aliased package rules loads all rules for original package too #8902
  src/Composer/DependencyResolver/Rule.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  tests/Composer/Test/Fixtures/installer/github-issues-8902.test
Labels: Bug

#8942 Fix unfixing of packages when a replacer gets unfixed before a replacee
  src/Composer/DependencyResolver/PoolBuilder.php
Labels: Bug

#8923 Autoload-Generator: support glob patterns in classmaps
  src/Composer/Autoload/ClassMapGenerator.php
Labels: Feature

#8937 Optimize rule creation for alias packages
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/Package/AliasPackage.php
  tests/Composer/Test/Fixtures/installer/alias-solver-problems.test
  tests/Composer/Test/Fixtures/installer/alias-solver-problems2.test
Labels: Solver

#8980 Discard changes is incomplete if Git project has additional folders
  src/Composer/Downloader/GitDownloader.php
Labels: Feature

#8982 Fix inline aliases not being loaded when extracting dev requirements
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/Repository/RepositorySet.php
  tests/Composer/Test/Fixtures/installer/aliases-with-require-dev.test
Labels: Bug

#8952 Parallel zip installs
  src/Composer/Command/ArchiveCommand.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Downloader/ArchiveDownloader.php
  src/Composer/Downloader/FileDownloader.php
  src/Composer/Downloader/GzipDownloader.php
  src/Composer/Downloader/PathDownloader.php
  src/Composer/Downloader/RarDownloader.php
  src/Composer/Downloader/XzDownloader.php
  src/Composer/Downloader/ZipDownloader.php
  src/Composer/Factory.php
  src/Composer/IO/ConsoleIO.php
  src/Composer/Installer.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Util/Http/CurlDownloader.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/Loop.php
  src/Composer/Util/ProcessExecutor.php
  src/Composer/Util/RemoteFilesystem.php
  tests/Composer/Test/Downloader/FileDownloaderTest.php
  tests/Composer/Test/Downloader/XzDownloaderTest.php
  tests/Composer/Test/Downloader/ZipDownloaderTest.php
  tests/Composer/Test/Repository/ComposerRepositoryTest.php
Labels: Feature

#8845 Use compiled constraint in Composer
  src/Composer/DependencyResolver/Pool.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/Repository/ComposerRepository.php
Labels: Feature

#8975 Composer 2: Allow plugins to override the URL before triggering the download
  src/Composer/Downloader/FileDownloader.php
  src/Composer/Plugin/PreFileDownloadEvent.php
  src/Composer/Repository/ComposerRepository.php
Labels: Feature

#8957 [1.10] Replace whitelist with allow list
  doc/01-basic-usage.md
  doc/03-cli.md
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Autoload/ClassMapGenerator.php
  src/Composer/Cache.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/DependencyResolver/Pool.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/Installer.php
  src/Composer/Package/BasePackage.php
  src/Composer/Repository/Vcs/GitHubDriver.php
  tests/Composer/Test/Fixtures/installer/github-issues-4795-2.test
  tests/Composer/Test/Fixtures/installer/github-issues-4795.test
  tests/Composer/Test/Fixtures/installer/install-from-lock-removes-package.test
  tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test
  tests/Composer/Test/Fixtures/installer/partial-update-forces-dev-reference-from-lock-for-non-updated-packages.test
  tests/Composer/Test/Fixtures/installer/partial-update-without-lock.test
  tests/Composer/Test/Fixtures/installer/update-changes-url.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-locked-require.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-patterns-with-all-dependencies.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-patterns-with-dependencies.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-patterns-with-root-dependencies.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-patterns-without-dependencies.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-patterns.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-removes-unused.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-with-dependencies.test
  tests/Composer/Test/Fixtures/installer/update-whitelist-with-dependency-conflict.test
  tests/Composer/Test/Fixtures/installer/update-whitelist.test
  tests/Composer/Test/Fixtures/installer/update-with-all-dependencies.test
  tests/Composer/Test/InstallerTest.php
Labels: Refactoring

#8993 GitDriver: use authentication for supports check
  src/Composer/Repository/Vcs/GitDriver.php
Labels: Bug

#8999 Fix solver bug exception 7051
  src/Composer/DependencyResolver/Pool.php
  src/Composer/DependencyResolver/Solver.php
  tests/Composer/Test/Fixtures/installer/github-issues-7051.test
Labels: Bug
