Repository composer/composer, pull requests merged in 2021-11, with the labels that each got.

#10249 Fix handling of php bin proxies combined with declare() on php <8
  src/Composer/Installer/BinaryInstaller.php
  tests/Composer/Test/Installer/BinaryInstallerTest.php
Labels: Bug

#10257 Update what GitHub token scope is needed and what it implies
  doc/articles/authentication-for-private-packages.md
Labels: Documentation

#10218 Read first from $_SERVER and $_ENV before using getenv
  src/Composer/Cache.php
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/GlobalCommand.php
  src/Composer/Config.php
  src/Composer/Console/Application.php
  src/Composer/Console/GithubActionError.php
  src/Composer/Downloader/GitDownloader.php
  src/Composer/Downloader/PathDownloader.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Factory.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Package/Loader/RootPackageLoader.php
  src/Composer/Repository/PathRepository.php
  src/Composer/Util/Git.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/Platform.php
  src/Composer/Util/StreamContextFactory.php
  tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
Labels: Feature

#10065 Fix loading files section for plugins
  src/Composer/Autoload/AutoloadGenerator.php
Labels: Feature

#10162 Add retry behavior on certain http status and curl error codes
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Util/Http/CurlDownloader.php
Labels: Feature

#10079 Refactor ignore platform reqs checks
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilter.php
  src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
  src/Composer/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilter.php
  src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterFactory.php
  src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterInterface.php
  src/Composer/Installer.php
  src/Composer/Package/Version/VersionSelector.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilterTest.php
  tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilterTest.php
  tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilterTest.php
  tests/Composer/Test/Filter/PlatformRequirementFilter/PlatformRequirementFilterFactoryTest.php
  tests/Composer/Test/InstallerTest.php
  tests/Composer/Test/Package/Version/VersionSelectorTest.php
Labels: Feature

#10129 Config: add source option for command to show where a config value is loaded from
  doc/03-cli.md
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DiagnoseCommand.php
  src/Composer/Config.php
  src/Composer/Factory.php
  tests/Composer/Test/ConfigTest.php
Labels: Feature

#10083 Add wildcard support to ignore platform req
  doc/03-cli.md
  src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
  src/Composer/Package/BasePackage.php
  src/Composer/Repository/FilterRepository.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilterTest.php
  tests/Composer/Test/Fixtures/installer/install-ignore-platform-package-requirement-list.test
  tests/Composer/Test/Fixtures/installer/install-ignore-platform-package-requirement-wildcard.test
  tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list.test
  tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-wildcard.test
  tests/Composer/Test/Package/BasePackageTest.php
Labels: Feature

#10274 Add name sorting to ArchivableFilesFinder.
  src/Composer/Package/Archiver/ArchivableFilesFinder.php
Labels: Bug

#10279 Fix loading files for plugins/scripts
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Plugin/PluginManager.php
Labels: Bug

#10281 Explicitly deprecate misuse of the link setters to enforce the fact they expect maps
  src/Composer/Package/Loader/ArrayLoader.php
  src/Composer/Package/Package.php
  src/Composer/Package/PackageInterface.php
  src/Composer/Repository/PlatformRepository.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/DependencyResolver/SolverTest.php
Labels: Refactoring

#10253 Upgrade PHPStan to 1.0
  .github/workflows/phpstan.yml
  composer.json
  phpstan/baseline.neon
  phpstan/config.neon
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Autoload/ClassLoader.php
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/Command/CheckPlatformReqsCommand.php
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/FundCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Console/HtmlOutputFormatter.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/Downloader/PerforceDownloader.php
  src/Composer/Downloader/ZipDownloader.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Installer/SuggestedPackagesReporter.php
  src/Composer/Package/Package.php
  src/Composer/Plugin/PluginManager.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Repository/PackageRepository.php
  src/Composer/Repository/PathRepository.php
  src/Composer/Repository/RepositoryFactory.php
  src/Composer/Util/Http/CurlDownloader.php
  src/Composer/Util/Http/ProxyHelper.php
  src/Composer/Util/Http/ProxyManager.php
  src/Composer/Util/Http/Response.php
  src/Composer/Util/Perforce.php
  src/Composer/Util/StreamContextFactory.php
  src/Composer/Util/Svn.php
  tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
  tests/Composer/Test/InstallerTest.php
  tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php
Labels: Needs Work

#10288 GitDownloader: add option for single use git clone to avoid --dissociate flag when cloning from local copy
  src/Composer/Downloader/GitDownloader.php
Labels: Feature

#10289 Docs: add transport options example and differentiate between cURL and stream options
  doc/05-repositories.md
Labels: Documentation

#10280 Fix unlocking of replacers when a replaced package is unlocked
  src/Composer/DependencyResolver/PoolBuilder.php
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/multi-repo-replace-partial-update-all.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-replacers.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-with-replacers-providers.test
  tests/Composer/Test/Fixtures/installer/github-issues-4795.test
  tests/Composer/Test/Fixtures/installer/partial-update-with-dependencies-provide.test
  tests/Composer/Test/Fixtures/installer/partial-update-with-dependencies-replace.test
  tests/Composer/Test/Fixtures/installer/partial-update-with-deps-warns-root.test
  tests/deprecations-8.1.json
Labels: Bug

#10293 Support ignore-platform-reqs in `composer outdated`
  doc/03-cli.md
  src/Composer/Command/OutdatedCommand.php
  src/Composer/Command/ShowCommand.php
Labels: Feature

#10262 Add COMPOSER_NO_DEV environment variable
  doc/03-cli.md
  src/Composer/Command/BaseCommand.php
Labels: Feature

#10309 Archiving fixes/tweaks
  src/Composer/Package/Archiver/ArchivableFilesFinder.php
  src/Composer/Package/Archiver/GitExcludeFilter.php
  src/Composer/Package/Archiver/HgExcludeFilter.php
  tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php
  tests/Composer/Test/Package/Archiver/GitExcludeFilterTest.php
  tests/Composer/Test/Package/Archiver/HgExcludeFilterTest.php
Labels: Feature

#10137 Expose path to autoload in a global var for binaries
  doc/04-schema.md
  doc/06-config.md
  doc/07-runtime.md
  doc/articles/vendor-binaries.md
  res/composer-schema.json
  src/Composer/Composer.php
  src/Composer/Config.php
  src/Composer/Factory.php
  src/Composer/Installer/BinaryInstaller.php
  src/Composer/Installer/LibraryInstaller.php
Labels: Feature

#10308 Add support for setting platform packages to false to disable them
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/Package/Loader/ValidatingArrayLoader.php
  src/Composer/Repository/PlatformRepository.php
  tests/Composer/Test/Fixtures/installer/solver-problems-with-disabled-platform.test
  tests/deprecations-8.1.json
Labels: Feature

#10157 Prevent auto-unlocked path repo packages from also unlocking their transitive deps when -w/-W is used
  src/Composer/DependencyResolver/PoolBuilder.php
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/mirrored-path-repo/composer.json
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repo-replacer-with-transitive-deps.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repos-always-but-not-their-transitive-deps.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo-replacer/composer.json
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo-with-replaced-deps/composer.json
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo/composer.json
  tests/Composer/Test/DependencyResolver/PoolBuilderTest.php
  tests/Composer/Test/Fixtures/installer/partial-update-with-symlinked-path-repos.test
  tests/deprecations-8.1.json
Labels: Bug

#10089 Feature proposal: sorting keys by logical blocks
  res/composer-schema.json
Labels: Feature

#10312 Allow recursively call composerRequire
  src/Composer/Autoload/AutoloadGenerator.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php
  tests/Composer/Test/Fixtures/functional/installed-versions2/vendor/composer/autoload_real.php
Labels: Bug

#10283 Better hint for missing extensions
  src/Composer/DependencyResolver/SolverProblemsException.php
  tests/Composer/Test/Fixtures/installer/platform-ext-solver-problems.test
  tests/Composer/Test/Fixtures/installer/solver-problems-with-disabled-platform.test
  tests/Composer/Test/Fixtures/installer/solver-problems.test
Labels: Feature

#10313 Add documentation on platform dependencies
  doc/articles/composer-platform-dependencies.md
  src/Composer/Repository/PlatformRepository.php
  tests/Composer/Test/Repository/PlatformRepositoryTest.php
Labels: Feature
