Repository composer/composer, pull requests merged in 2021-12, with the labels that each got.

#10327 Install full binaries on Windows by default
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10307 [FEATURE] Configure automatic yes for composer.json in upper directory
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/ConfigCommand.php
  src/Composer/Config.php
  src/Composer/Console/Application.php
Labels: Feature

#10318 Add support for ignoring the upper bound of platform requirements using "name+" notation
  composer.json
  doc/03-cli.md
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
  src/Composer/Installer.php
  tests/Composer/Test/Fixtures/installer/platform-ext-solver-problems.test
  tests/Composer/Test/Fixtures/installer/solver-problems.test
  tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
  tests/deprecations-8.1.json
Labels: Feature

#10087 Document archive --format=tar.gz
  doc/03-cli.md
Labels: Documentation

#10314 Add allow-plugins config value
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/ConfigCommand.php
  src/Composer/Config.php
  src/Composer/Config/JsonConfigSource.php
  src/Composer/Plugin/PluginManager.php
  tests/Composer/Test/Fixtures/functional/installed-versions/composer.json
  tests/Composer/Test/Fixtures/functional/installed-versions2/composer.json
  tests/Composer/Test/Plugin/PluginInstallerTest.php
Labels: Feature

#9620 Filter impossible packages from the pool
  src/Composer/DependencyResolver/PoolOptimizer.php
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repos-always-but-not-their-transitive-deps.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-locked-deps.test
Labels: Solver, Feature

#10336 Search improvements
  doc/03-cli.md
  src/Composer/Cache.php
  src/Composer/Command/SearchCommand.php
  src/Composer/Repository/ArrayRepository.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Repository/PlatformRepository.php
  src/Composer/Repository/RepositoryInterface.php
Labels: Feature, Bug

#9826 Update InstallCommand.php
  src/Composer/Command/InstallCommand.php
Labels: Feature

#10363 $home -> $COMPOSER_HOME (doc: config)
  doc/06-config.md
Labels: Documentation

#10372 Switch the default version in path repo packages to dev-main
  src/Composer/Repository/PathRepository.php
Labels: Feature

#10371 Add --no-scripts to all commands and disable plugins/scripts when running self-update
  doc/03-cli.md
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Console/Application.php
  src/Composer/Factory.php
  tests/Composer/Test/ApplicationTest.php
Labels: Bug

#10373 Disable files autoloading for scripts to avoid untrusted code execution at runtime
  src/Composer/EventDispatcher/EventDispatcher.php
Labels: Bug

#10377 Use web URL for Gitlab support metadata
  src/Composer/Repository/Vcs/GitLabDriver.php
  tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
Labels: Bug

#10386 Fix plugin autoloading including files autoload rules from the root package
  src/Composer/Plugin/PluginManager.php
  tests/Composer/Test/Plugin/Fixtures/files_autoload_which_should_not_run.php
  tests/Composer/Test/Plugin/PluginInstallerTest.php
Labels: Bug

#10402 Make COMPOSER_BIN_DIR env or _composer_bin_dir global available to binaries
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10404 Fix symfony error handler warnings, fixes #10397
  src/Composer/Console/Application.php
  src/Composer/IO/BaseIO.php
Labels: Bug

#10405 fix: Do not optimise away packages due to a requirement by a locked package that will be uninstalled
  src/Composer/DependencyResolver/PoolOptimizer.php
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-locked-replacer.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required-provides.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required-replaces.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-provides.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-replaces.test
  tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages.test
Labels: Bug
