Repository composer/composer, pull requests merged in 2021-05, with the labels that each got.

#9855 BinaryInstaller: install full binaries on WSL when bin-compat=auto
  src/Composer/Installer/BinaryInstaller.php
  src/Composer/Util/Platform.php
Labels: Feature

#9861 Introduce a cross-platform safe version of is_readable to support UNC / wsl$ paths on Windows
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Autoload/ClassMapGenerator.php
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Command/ValidateCommand.php
  src/Composer/Config/JsonConfigSource.php
  src/Composer/Console/Application.php
  src/Composer/Installer/LibraryInstaller.php
  src/Composer/Util/Filesystem.php
  src/Composer/Util/StreamContextFactory.php
Labels: Bug

#9864 Hint at a branch rename if we detect dev-master can not be found and condense dev-* versions in problem output
  src/Composer/DependencyResolver/Problem.php
  tests/Composer/Test/Fixtures/installer/hint-main-rename.test
Labels: Feature

#9887 Use a simpler suggested require version of * to keep things simple for extensions which are versioned like PHP
  src/Composer/Package/Version/VersionSelector.php
  tests/Composer/Test/Package/Version/VersionSelectorTest.php
Labels: Feature

#9873 Add Platform-PHP version to user-agent header to improve targetted-php stats
  src/Composer/Repository/PlatformRepository.php
  src/Composer/Util/StreamContextFactory.php
Labels: Feature

#9816 Deprecate InstalledVersions::getRawData in favor of getAllRawData
  src/Composer/InstalledVersions.php
Labels: Refactoring

#9401 Introduce gitlab-protocol option to force source repository URL (e.g., to HTTPS)
  doc/06-config.md
  src/Composer/Config.php
  src/Composer/Repository/Vcs/GitLabDriver.php
  tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
Labels: Feature

#9898 macOS cache dir
  doc/06-config.md
  src/Composer/Factory.php
Labels: Feature

#9915 Add a reinstall command
  doc/03-cli.md
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Console/Application.php
Labels: Feature
