Repository composer/composer, pull requests merged in 2021-06, with the labels that each got.

#9899 Detect missing packages that are a requirement or dev-requirement but not locked
  src/Composer/Command/ValidateCommand.php
Labels: Feature

#9925 Add support for mirror-style placeholders for the dist url
  src/Composer/Package/Package.php
  src/Composer/Util/ComposerMirror.php
Labels: Feature

#9928 Add better error reporting for cases where a package conflicts with a replace and not directly a package
  src/Composer/DependencyResolver/Rule.php
  tests/Composer/Test/Fixtures/installer/conflict-against-provided-by-dep-package-works.test
  tests/Composer/Test/Fixtures/installer/conflict-against-provided-package-works.test
  tests/Composer/Test/Fixtures/installer/conflict-against-replaced-by-dep-package-problem.test
  tests/Composer/Test/Fixtures/installer/conflict-against-replaced-package-problem.test
Labels: Feature

#9875 Speedup extracting on Windows
  src/Composer/Command/DiagnoseCommand.php
  src/Composer/Downloader/ArchiveDownloader.php
  src/Composer/Downloader/FileDownloader.php
  src/Composer/Downloader/ZipDownloader.php
  tests/Composer/Test/Downloader/ZipDownloaderTest.php
  tests/Composer/Test/Fixtures/functional/installed-versions.test
  tests/Composer/Test/Fixtures/functional/installed-versions2.test
Labels: Feature

#9935 Fix autoload generation for dev dependencies when --no-scripts is used
  src/Composer/Autoload/AutoloadGenerator.php
Labels: Bug

#9941 Workaround for PCRE regression
  src/Composer/Util/Url.php
Labels: Bug

#9942 Fix --no-scripts disabling events for plugins
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Installer.php
Labels: Bug

#9959 Add "symlink" option for "bin-compat" config
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/ConfigCommand.php
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug, Feature
