Repository composer/composer, pull requests merged in 2022-12, with the labels that each got.

#11188 Allow storing credentials globally when 'local' auth.json file exists
  src/Composer/Config.php
  src/Composer/Factory.php
  src/Composer/Util/Bitbucket.php
  src/Composer/Util/GitHub.php
  src/Composer/Util/GitLab.php
Labels: Feature

#11195 Check missing required packages when running install and fail when there are any
  phpstan/baseline.neon
  src/Composer/Command/ValidateCommand.php
  src/Composer/Installer.php
  src/Composer/Package/Locker.php
  tests/Composer/Test/Fixtures/installer/install-from-empty-lock.test
  tests/Composer/Test/Fixtures/installer/install-from-incomplete-lock.test
Labels: Feature

#11230 Improve version selection in archive command
  phpstan/baseline-8.1.neon
  phpstan/baseline.neon
  src/Composer/Command/ArchiveCommand.php
Labels: Feature

#11229 Allow underscores in cache keys to avoid conflicts with package names containing underscore vs dashes
  src/Composer/Cache.php
  src/Composer/Repository/ComposerRepository.php
Labels: Bug, Backport-2.2

#11233 Docs: fix documention deep links
  CHANGELOG.md
  src/Composer/Command/DependsCommand.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/ProhibitsCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/RunScriptCommand.php
  src/Composer/Command/ScriptAliasCommand.php
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Package/Locker.php
  tests/Composer/Test/Command/ValidateCommandTest.php
  tests/Composer/Test/Fixtures/installer/install-from-incomplete-lock.test
  tests/Composer/Test/Fixtures/installer/root-requirements-do-not-affect-locked-versions.test
Labels: Bug

#11154 Document recovering from invalid merges on composer.lock and composer.json
  doc/03-cli.md
  doc/articles/resolving-merge-conflicts.md
Labels: Documentation

#11237 Fix ClassLoader to be serializable
  .github/workflows/continuous-integration.yml
  src/Composer/Autoload/ClassLoader.php
  tests/Composer/Test/Autoload/ClassLoaderTest.php
Labels: Bug
