Repository composer/composer, pull requests merged in 2022-01, with the labels that each got.

#10420 Cleanup PHP 5.3 hacks and legacy TODOs
  composer.json
  phpstan/Rules/src/AnonymousFunctionWithThisRule.php
  phpstan/Rules/tests/AnonymousFunctionWithThisRuleTest.php
  phpstan/Rules/tests/data/method-with-this.php
  phpstan/config.neon
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/LicensesCommand.php
  src/Composer/Compiler.php
  src/Composer/Config.php
  src/Composer/Console/Application.php
  src/Composer/Console/HtmlOutputFormatter.php
  src/Composer/DependencyResolver/DefaultPolicy.php
  src/Composer/Downloader/ArchiveDownloader.php
  src/Composer/Downloader/DownloadManager.php
  src/Composer/Downloader/FileDownloader.php
  src/Composer/Downloader/ZipDownloader.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Installer/LibraryInstaller.php
  src/Composer/Installer/PluginInstaller.php
  src/Composer/Json/JsonManipulator.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Util/Filesystem.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/Perforce.php
  src/Composer/Util/ProcessExecutor.php
  src/Composer/Util/RemoteFilesystem.php
  tests/Composer/Test/AllFunctionalTest.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Downloader/FileDownloaderTest.php
  tests/Composer/Test/Package/BasePackageTest.php
  tests/Composer/Test/Repository/ComposerRepositoryTest.php
  tests/Composer/Test/Util/GitTest.php
Labels: Refactoring

#10417 Remove codeblocks for php 5 compatibilities
  src/Composer/Autoload/ClassMapGenerator.php
  src/Composer/Cache.php
  src/Composer/Command/DiagnoseCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Console/Application.php
  src/Composer/Factory.php
  src/Composer/Json/JsonFile.php
  src/Composer/Json/JsonFormatter.php
  src/Composer/Package/Archiver/ZipArchiver.php
  src/Composer/Util/Git.php
  src/Composer/Util/RemoteFilesystem.php
  src/Composer/Util/StreamContextFactory.php
  tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
  tests/Composer/Test/Json/JsonFileTest.php
  tests/Composer/Test/Platform/HhvmDetectorTest.php
  tests/Composer/Test/Util/RemoteFilesystemTest.php
Labels: Refactoring

#10428 Deprecations & more php version cleanups
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Json/JsonFile.php
  src/Composer/Json/JsonFormatter.php
  src/Composer/Package/Locker.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/RemoteFilesystem.php
  src/Composer/Util/TlsHelper.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap2.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap3.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap4.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap5.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap6.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap7.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap8.php
  tests/Composer/Test/Autoload/Fixtures/autoload_classmap9.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files2.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files_files_by_dependency.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files_functions.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files_functions_with_removed_extra.php
  tests/Composer/Test/Autoload/Fixtures/autoload_files_target_dir.php
  tests/Composer/Test/Autoload/Fixtures/autoload_main.php
  tests/Composer/Test/Autoload/Fixtures/autoload_main2.php
  tests/Composer/Test/Autoload/Fixtures/autoload_main3.php
  tests/Composer/Test/Autoload/Fixtures/autoload_main4.php
  tests/Composer/Test/Autoload/Fixtures/autoload_main5.php
  tests/Composer/Test/Autoload/Fixtures/autoload_phar.php
  tests/Composer/Test/Autoload/Fixtures/autoload_phar_psr4.php
  tests/Composer/Test/Autoload/Fixtures/autoload_psr4.php
  tests/Composer/Test/Autoload/Fixtures/autoload_psr4_2.php
  tests/Composer/Test/Autoload/Fixtures/autoload_psr4_3.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_removed_include_paths_and_autolad_files.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_include_path.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php
  tests/Composer/Test/Autoload/Fixtures/autoload_vendors.php
  tests/Composer/Test/Autoload/Fixtures/include_paths.php
  tests/Composer/Test/Autoload/Fixtures/include_paths_functions.php
  tests/Composer/Test/Autoload/Fixtures/include_paths_functions_with_removed_extra.php
  tests/Composer/Test/Installer/BinaryInstallerTest.php
  tests/Composer/Test/InstallerTest.php
  tests/Composer/Test/Json/JsonFileTest.php
  tests/Composer/Test/Json/JsonFormatterTest.php
  tests/Composer/Test/Util/TlsHelperTest.php
Labels: Refactoring

#10430 Add links to repo to show/outdated commands package lists
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/FundCommand.php
  src/Composer/Command/LicensesCommand.php
  src/Composer/Command/SearchCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Repository/RepositoryInterface.php
  src/Composer/Util/PackageInfo.php
Labels: Feature

#10416 Allow xdebug-handler 3.x, update deps
  composer.json
  composer.lock
Labels: Feature

#10435 Allow ProcessExecutor to receive commands as arrays
  phpstan/baseline-8.1.neon
  phpstan/baseline.neon
  src/Composer/Package/Version/VersionGuesser.php
  src/Composer/Util/ProcessExecutor.php
  tests/Composer/Test/Mock/ProcessExecutorMock.php
  tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php
  tests/Composer/Test/Package/Version/VersionGuesserTest.php
Labels: Feature

#10440 GitLab: detect repository functionality disabled in Driver
  src/Composer/Repository/Vcs/GitLabDriver.php
Labels: Bug

#10432 Fix #10366: Improve messaging when GitHub tokens need SSO authorization
  src/Composer/Util/AuthHelper.php
  src/Composer/Util/GitHub.php
Labels: Bug

#10454 Allow psr/log ^3.0
  composer.json
  composer.lock
Labels: Feature

#10446 Use copy in selfupdate to fix Windows PHP-8.1 regression
  src/Composer/Command/SelfUpdateCommand.php
Labels: Bug

#10468 Add stream_seek to BinProxyWrapper
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10463 report error if binary is a directory
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10470 ArrayLoader: handle none string values for version/version_normalized
  src/Composer/Package/Loader/ArrayLoader.php
  src/Composer/Package/Loader/ValidatingArrayLoader.php
  tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Labels: Bug

#10477 Improve documentation
  doc/03-cli.md
Labels: Documentation
