Repository composer/composer, pull requests merged in 2022-02, with the labels that each got.

#10485 Add abandoned flag to show/outdated commands package lists
  src/Composer/Command/ShowCommand.php
Labels: Feature

#10512 Rename COMPOSER_BIN_DIR (in bin proxies) to COMPOSER_RUNTIME_BIN_DIR
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10514 Fix reinstall command not firing pre-install-cmd/post-install-cmd events
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Repository/FilesystemRepository.php
  src/Composer/Repository/InstalledRepositoryInterface.php
  src/Composer/Repository/WritableArrayRepository.php
Labels: Bug

#10488 Add config option for update reference in path repository
  doc/05-repositories.md
  src/Composer/Repository/PathRepository.php
  tests/Composer/Test/Repository/PathRepositoryTest.php
Labels: Feature

#10525 VcsRepositories: handle initialize with invalid repository URL
  src/Composer/Repository/Vcs/GitBitbucketDriver.php
  src/Composer/Repository/Vcs/GitHubDriver.php
  src/Composer/Repository/Vcs/GitLabDriver.php
  tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php
  tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Labels: Bug

#10537 Handle missing license when showing license summary
  src/Composer/Command/LicensesCommand.php
Labels: Bug

#10476 Add phpstan-symfony & some refactorings
  composer.json
  composer.lock
  doc/articles/plugins.md
  phpstan/baseline-8.1.neon
  phpstan/baseline.neon
  phpstan/config.neon
  src/Composer/Command/AboutCommand.php
  src/Composer/Command/ArchiveCommand.php
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/Command/CheckPlatformReqsCommand.php
  src/Composer/Command/ClearCacheCommand.php
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DependsCommand.php
  src/Composer/Command/DiagnoseCommand.php
  src/Composer/Command/DumpAutoloadCommand.php
  src/Composer/Command/ExecCommand.php
  src/Composer/Command/FundCommand.php
  src/Composer/Command/HomeCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/LicensesCommand.php
  src/Composer/Command/OutdatedCommand.php
  src/Composer/Command/PackageDiscoveryTrait.php
  src/Composer/Command/ProhibitsCommand.php
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/RunScriptCommand.php
  src/Composer/Command/ScriptAliasCommand.php
  src/Composer/Command/SearchCommand.php
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Command/StatusCommand.php
  src/Composer/Command/SuggestsCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Command/ValidateCommand.php
  src/Composer/Config/ConfigSourceInterface.php
  src/Composer/Config/JsonConfigSource.php
  src/Composer/EventDispatcher/EventDispatcher.php
  src/Composer/IO/IOInterface.php
  src/Composer/Util/Git.php
  src/Composer/Util/Http/CurlDownloader.php
  tests/Composer/Test/ApplicationTest.php
  tests/Composer/Test/Command/ArchiveCommandTest.php
  tests/Composer/Test/Command/RunScriptCommandTest.php
  tests/Composer/Test/Mock/HttpDownloaderMock.php
  tests/Composer/Test/Mock/ProcessExecutorMock.php
  tests/Composer/Test/Plugin/Fixtures/plugin-v8/Installer/CommandProvider.php
  tests/console-application.php
Labels: Refactoring

#10516 Introduce phpstan-type about autoload array type to be DRY
  src/Composer/Package/Package.php
  src/Composer/Package/PackageInterface.php
  src/Composer/Package/RootPackageInterface.php
Labels: Refactoring

#10565 Add visibility to all consts, fixes #10550
  .php-cs-fixer.php
  phpstan/baseline.neon
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Command/StatusCommand.php
  src/Composer/Composer.php
  src/Composer/Config.php
  src/Composer/DependencyResolver/Decisions.php
  src/Composer/DependencyResolver/Operation/InstallOperation.php
  src/Composer/DependencyResolver/Operation/MarkAliasInstalledOperation.php
  src/Composer/DependencyResolver/Operation/MarkAliasUninstalledOperation.php
  src/Composer/DependencyResolver/Operation/SolverOperation.php
  src/Composer/DependencyResolver/Operation/UninstallOperation.php
  src/Composer/DependencyResolver/Operation/UpdateOperation.php
  src/Composer/DependencyResolver/Request.php
  src/Composer/DependencyResolver/Rule.php
  src/Composer/DependencyResolver/RuleSet.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/DependencyResolver/SolverProblemsException.php
  src/Composer/Downloader/PathDownloader.php
  src/Composer/IO/IOInterface.php
  src/Composer/Installer.php
  src/Composer/Installer/InstallerEvents.php
  src/Composer/Installer/PackageEvents.php
  src/Composer/Installer/SuggestedPackagesReporter.php
  src/Composer/Json/JsonFile.php
  src/Composer/Package/BasePackage.php
  src/Composer/Package/Link.php
  src/Composer/Package/Loader/LoaderInterface.php
  src/Composer/Package/Loader/ValidatingArrayLoader.php
  src/Composer/Package/PackageInterface.php
  src/Composer/Package/RootPackage.php
  src/Composer/Package/Version/VersionParser.php
  src/Composer/Plugin/PluginEvents.php
  src/Composer/Plugin/PluginInterface.php
  src/Composer/Repository/PlatformRepository.php
  src/Composer/Repository/RepositoryInterface.php
  src/Composer/Repository/RepositorySet.php
  src/Composer/Repository/Vcs/GitLabDriver.php
  src/Composer/Script/ScriptEvents.php
  src/Composer/Util/Bitbucket.php
  src/Composer/Util/ConfigValidator.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/ProcessExecutor.php
  src/Composer/Util/Svn.php
  src/bootstrap.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Command/InitCommandTest.php
  tests/Composer/Test/Repository/PlatformRepositoryTest.php
  tests/Composer/Test/Repository/Vcs/PerforceDriverTest.php
  tests/Composer/Test/Util/PerforceTest.php
Labels: Refactoring
