Repository composer/composer, pull requests merged in 2022-08, with the labels that each got.

#10982 Add SearchCommand tests
  tests/Composer/Test/Command/SearchCommandTest.php
Labels: Refactoring

#10985 GitHubDriver: stricter URL validation to avoid issues with undefined index owner
  src/Composer/Repository/Vcs/GitHubDriver.php
  tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Labels: Bug

#10994 Correct prohibits/why-not example command
  doc/03-cli.md
Labels: Documentation

#10988 Added token refresh for GitLab
  phpstan/baseline.neon
  res/composer-schema.json
  src/Composer/IO/BaseIO.php
  src/Composer/Repository/Vcs/GitLabDriver.php
  src/Composer/Util/GitLab.php
  tests/Composer/Test/Util/GitLabTest.php
Labels: Feature

#10979 CheckPlatformReqs: basic json format support
  doc/03-cli.md
  src/Composer/Command/CheckPlatformReqsCommand.php
Labels: Feature

#10996 Only fetch remote default branch for mirrored git repos, not local ones
  src/Composer/Repository/Vcs/GitDriver.php
  tests/Composer/Test/Repository/Vcs/GitDriverTest.php
Labels: Bug

#10998 Environment variable for `--no-audit`.
  doc/03-cli.md
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/UpdateCommand.php
Labels: Feature

#11000 Show/outdated command fixes
  src/Composer/Command/ShowCommand.php
  src/Composer/Repository/RepositoryUtils.php
  tests/Composer/Test/Command/ShowCommandTest.php
Labels: Bug

#11010 Match default choice to actual default
  src/Composer/Command/SelfUpdateCommand.php
Labels: Bug, Backport-2.2

#11004 Fix cache invalidation issue when a git tag gets created on an old ref after the cache is populated
  src/Composer/Downloader/GitDownloader.php
  src/Composer/Util/Git.php
Labels: Bug, Backport-2.2

#11009 Do not apply non-string package link constraints in ArrayLoader
  src/Composer/Package/Loader/ArrayLoader.php
  tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Labels: Bug

#11013 Adding hint what "Direct dependencies" means
  src/Composer/Command/ShowCommand.php
  tests/Composer/Test/Command/ShowCommandTest.php
Labels: Documentation

#11011 Documentation code syntax highlighting
  doc/00-intro.md
  doc/01-basic-usage.md
  doc/03-cli.md
  doc/04-schema.md
  doc/05-repositories.md
  doc/articles/aliases.md
  doc/articles/authentication-for-private-packages.md
  doc/articles/composer-platform-dependencies.md
  doc/articles/handling-private-packages.md
  doc/articles/plugins.md
  doc/articles/resolving-merge-conflicts.md
  doc/articles/scripts.md
  doc/articles/troubleshooting.md
  doc/articles/versions.md
  doc/faqs/how-to-install-composer-programmatically.md
  doc/faqs/how-to-install-untrusted-packages-safely.md
Labels: Documentation

#11015 Lock down include wrappers to avoid abuse from third parties
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Autoload/ClassLoader.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php
  tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php
Labels: Feature
