Repository composer/composer, pull requests merged in 2022-06, with the labels that each got.

#10320 Add completion to commands options and arguments
  doc/03-cli.md
  src/Composer/Cache.php
  src/Composer/Command/ArchiveCommand.php
  src/Composer/Command/BaseCommand.php
  src/Composer/Command/CompletionTrait.php
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Command/DependsCommand.php
  src/Composer/Command/ExecCommand.php
  src/Composer/Command/FundCommand.php
  src/Composer/Command/GlobalCommand.php
  src/Composer/Command/HomeCommand.php
  src/Composer/Command/InitCommand.php
  src/Composer/Command/InstallCommand.php
  src/Composer/Command/LicensesCommand.php
  src/Composer/Command/OutdatedCommand.php
  src/Composer/Command/PackageDiscoveryTrait.php
  src/Composer/Command/ProhibitsCommand.php
  src/Composer/Command/ReinstallCommand.php
  src/Composer/Command/RemoveCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Command/RunScriptCommand.php
  src/Composer/Command/ScriptAliasCommand.php
  src/Composer/Command/SearchCommand.php
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Command/StatusCommand.php
  src/Composer/Command/SuggestsCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Console/Application.php
  src/Composer/Console/Input/InputArgument.php
  src/Composer/Console/Input/InputOption.php
  src/Composer/Factory.php
  src/Composer/Package/Version/VersionGuesser.php
  src/Composer/Util/Platform.php
  tests/Composer/Test/CompletionFunctionalTest.php
Labels: Feature

#9910 Add Docker information
  doc/00-intro.md
Labels: Documentation

#10812 plugins: mention static analysis support
  composer.json
  doc/articles/plugins.md
Labels: Documentation

#10780 WIP: Added documentation about HTTP Bearer Auth
  doc/articles/authentication-for-private-packages.md
Labels: Documentation

#10829 Add bump 👊🏻 command to bump requirements to the currently installed version
  doc/03-cli.md
  src/Composer/Command/BumpCommand.php
  src/Composer/Command/CompletionTrait.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Console/Application.php
  src/Composer/Package/Version/VersionBumper.php
  tests/Composer/Test/Command/BumpCommandTest.php
  tests/Composer/Test/Mock/FactoryMock.php
  tests/Composer/Test/Mock/InstallationManagerMock.php
  tests/Composer/Test/Package/Version/VersionBumperTest.php
  tests/Composer/Test/TestCase.php
Labels: Feature

#10827 Add --major-only flag to outdated/show commands to restrict the list to packages with major updates available
  doc/03-cli.md
  src/Composer/Command/OutdatedCommand.php
  src/Composer/Command/ShowCommand.php
Labels: Feature

#10826 Add --gc flag to clear-cache command and ability to GC vcs/repo caches
  doc/03-cli.md
  src/Composer/Cache.php
  src/Composer/Command/ClearCacheCommand.php
Labels: Feature

#10836 Fix exported path with space in binary installer proxy
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#10885 Make use of composer/class-map-generator and deprecate ClassMapGenerator class
  composer.json
  composer.lock
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Autoload/ClassMapGenerator.php
  tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
  tests/Composer/Test/Autoload/Fixtures/Namespaced/Bar.inc
  tests/Composer/Test/Autoload/Fixtures/Namespaced/Baz.php
  tests/Composer/Test/Autoload/Fixtures/Pearlike/Bar.php
  tests/Composer/Test/Autoload/Fixtures/Pearlike/Baz.php
  tests/Composer/Test/Autoload/Fixtures/beta/NamespaceCollision/A/B/Bar.php
  tests/Composer/Test/Autoload/Fixtures/beta/NamespaceCollision/A/B/Foo.php
  tests/Composer/Test/Autoload/Fixtures/beta/PrefixCollision/A/B/Bar.php
  tests/Composer/Test/Autoload/Fixtures/beta/PrefixCollision/A/B/Foo.php
  tests/Composer/Test/Autoload/Fixtures/classmap/BackslashLineEndingString.php
  tests/Composer/Test/Autoload/Fixtures/classmap/InvalidUnicode.php
  tests/Composer/Test/Autoload/Fixtures/classmap/LargeClass.php
  tests/Composer/Test/Autoload/Fixtures/classmap/LargeGap.php
  tests/Composer/Test/Autoload/Fixtures/classmap/LongString.php
  tests/Composer/Test/Autoload/Fixtures/classmap/MissingSpace.php
  tests/Composer/Test/Autoload/Fixtures/classmap/NonUnicode.php
  tests/Composer/Test/Autoload/Fixtures/classmap/ShortOpenTag.php
  tests/Composer/Test/Autoload/Fixtures/classmap/ShortOpenTagDocblock.php
  tests/Composer/Test/Autoload/Fixtures/classmap/SomeClass.php
  tests/Composer/Test/Autoload/Fixtures/classmap/SomeInterface.php
  tests/Composer/Test/Autoload/Fixtures/classmap/SomeParent.php
  tests/Composer/Test/Autoload/Fixtures/classmap/StripNoise.php
  tests/Composer/Test/Autoload/Fixtures/classmap/Unicode.php
  tests/Composer/Test/Autoload/Fixtures/classmap/multipleNs.php
  tests/Composer/Test/Autoload/Fixtures/classmap/notAClass.php
  tests/Composer/Test/Autoload/Fixtures/classmap/notPhpFile.md
  tests/Composer/Test/Autoload/Fixtures/classmap/sameNsMultipleClasses.php
  tests/Composer/Test/Autoload/Fixtures/hhvm3.3/Generics.php
  tests/Composer/Test/Autoload/Fixtures/hhvm3.3/HackEnum.php
  tests/Composer/Test/Autoload/Fixtures/hhvm3.3/NamespacedHackEnum.php
  tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/StripNoise.php
  tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongHeredoc.php
  tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongNowdoc.php
  tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongPHP73Heredoc.php
  tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongPHP73Nowdoc.php
  tests/Composer/Test/Autoload/Fixtures/php5.4/traits.php
  tests/Composer/Test/Autoload/Fixtures/php7.0/anonclass.php
  tests/Composer/Test/Autoload/Fixtures/php8.1/enum_backed.php
  tests/Composer/Test/Autoload/Fixtures/php8.1/enum_basic.php
  tests/Composer/Test/Autoload/Fixtures/php8.1/enum_class_semantics.php
  tests/Composer/Test/Autoload/Fixtures/php8.1/enum_namespaced.php
  tests/Composer/Test/Autoload/Fixtures/template/notphp.inc
  tests/Composer/Test/Autoload/Fixtures/template/template_1.php
  tests/Composer/Test/Autoload/Fixtures/template/template_2.php
  tests/Composer/Test/Autoload/Fixtures/template/template_3.php
  tests/Composer/Test/Fixtures/functional/installed-versions.test
  tests/Composer/Test/Fixtures/functional/installed-versions2.test
Labels: Feature

#10834 Allow use of --locked with depends and prohibits
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/Command/DependsCommand.php
  src/Composer/Command/ProhibitsCommand.php
Labels: Feature
