Repository composer/composer, pull requests merged in 2023-07, with the labels that each got.

#11505 docs: add binary dependencies
  README.md
  doc/00-intro.md
Labels: Documentation

#11308 Add source link to composer packages
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/Util/PackageInfo.php
Labels: Feature

#11390 Preserve indentation when writing JSON files
  src/Composer/Json/JsonFile.php
  src/Composer/Json/JsonManipulator.php
  tests/Composer/Test/Json/Fixtures/tabs.json
  tests/Composer/Test/Json/JsonFileTest.php
Labels: Feature

#11557 Update BinaryInstaller.php
  src/Composer/Installer/BinaryInstaller.php
Labels: Feature

#10429 Use Promise::done where possible, upgrade react/promise to allow v3
  composer.json
  composer.lock
  phpstan/baseline.neon
  src/Composer/Downloader/ArchiveDownloader.php
  src/Composer/Downloader/DownloadManager.php
  src/Composer/Downloader/DownloaderInterface.php
  src/Composer/Downloader/GitDownloader.php
  src/Composer/Downloader/SvnDownloader.php
  src/Composer/Downloader/VcsDownloader.php
  src/Composer/Downloader/ZipDownloader.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Installer/InstallerInterface.php
  src/Composer/Installer/LibraryInstaller.php
  src/Composer/Package/Version/VersionGuesser.php
  src/Composer/Repository/ComposerRepository.php
  src/Composer/Util/Filesystem.php
  src/Composer/Util/HttpDownloader.php
  src/Composer/Util/Loop.php
  src/Composer/Util/ProcessExecutor.php
  src/Composer/Util/SyncHelper.php
  tests/Composer/Test/Downloader/ZipDownloaderTest.php
  tests/Composer/Test/Util/ProcessExecutorTest.php
Labels: Feature

#11550 Fix broken junctions leads to installation failure
  src/Composer/Util/Filesystem.php
  tests/Composer/Test/Util/FilesystemTest.php
Labels: Bug

#11534 Fix lib-curl-openssl parsing for SecureTransport
  src/Composer/Repository/PlatformRepository.php
  tests/Composer/Test/Repository/PlatformRepositoryTest.php
Labels: Backport-2.2

#11533 Fix 'composer show --platform <package>' erroring without composer.json
  src/Composer/Command/ShowCommand.php
  tests/Composer/Test/Command/ShowCommandTest.php
Labels: Bug, Backport-2.2
