Repository composer/composer, pull requests merged in 2023-05, with the labels that each got.

#11454 Fixed binary proxies to return whatever the original binary returns as well
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug, Backport-2.2

#11453 Add support for env vars and ~ (for HOME) in repo paths for vcs/artifact repos
  src/Composer/Repository/ArtifactRepository.php
  src/Composer/Repository/VcsRepository.php
Labels: Feature

#11436 Support advisories from multiple repositories for the same package
  src/Composer/Repository/RepositorySet.php
Labels: Feature

#11455 Return null for install path for metapackages instead of an empty string as path
  doc/articles/custom-installers.md
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Command/ShowCommand.php
  src/Composer/Command/StatusCommand.php
  src/Composer/Command/ValidateCommand.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Installer/InstallerInterface.php
  src/Composer/Installer/LibraryInstaller.php
  src/Composer/Installer/MetapackageInstaller.php
  src/Composer/Installer/ProjectInstaller.php
  src/Composer/Package/Locker.php
  src/Composer/Plugin/PluginManager.php
Labels: Bug

#11464 Fix authentication issues with multiple private bitbucket repos
  src/Composer/Util/AuthHelper.php
  tests/Composer/Test/Util/AuthHelperTest.php
Labels: Bug

#11481 Fix autoload regression with metapackage dependencies
  src/Composer/Autoload/AutoloadGenerator.php
  tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
  tests/Composer/Test/Autoload/Fixtures/autoload_vendors_meta.php
Labels: Bug
