Repository composer/composer, pull requests merged in 2024-09, with the labels that each got.

#12109 Fix handling of COMPOSER_ROOT_VERSION to normalize according to expectations
  src/Composer/Package/Loader/RootPackageLoader.php
  src/Composer/Package/Version/VersionGuesser.php
  src/Composer/Repository/PathRepository.php
  tests/Composer/Test/Package/Version/VersionGuesserTest.php
Labels: Bug

#12110 Fix handling of platform packages in why-not command and partial updates
  src/Composer/Command/BaseDependencyCommand.php
  src/Composer/DependencyResolver/PoolBuilder.php
  tests/Composer/Test/Command/BaseDependencyCommandTest.php
Labels: Bug

#12091 Add `--abandoned` option
  doc/03-cli.md
  doc/06-config.md
  src/Composer/Advisory/Auditor.php
  src/Composer/Command/AuditCommand.php
  src/Composer/Config.php
Labels: Feature

#12113 Add suggestions of provider packages for ext- and lib- packages
  src/Composer/DependencyResolver/Problem.php
Labels: Feature

#12112 Fix require command skipping new stability-flags from the lock file, …
  src/Composer/Command/RequireCommand.php
  src/Composer/Package/Locker.php
Labels: Bug

#11990 Improve interactive package updates
  src/Composer/Command/UpdateCommand.php
  tests/Composer/Test/Command/UpdateCommandTest.php
Labels: Feature

#11966 Add allow-missing-requirements config setting to ignore missing requirements
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Config.php
  src/Composer/Installer.php
  tests/Composer/Test/Fixtures/installer/install-from-incomplete-lock-with-ignore.test
Labels: Feature

#12086 Add a way to control which scripts get args and where
  doc/articles/scripts.md
  src/Composer/EventDispatcher/EventDispatcher.php
  tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
Labels: Feature

#11942 Add option to run bump after update
  doc/03-cli.md
  doc/06-config.md
  res/composer-schema.json
  src/Composer/Command/BumpCommand.php
  src/Composer/Command/ConfigCommand.php
  src/Composer/Command/UpdateCommand.php
  src/Composer/Config.php
  tests/Composer/Test/Command/UpdateCommandTest.php
Labels: Feature

#12119 Add --strict-ambiguous to dump-autoload command
  doc/03-cli.md
  src/Composer/Command/DumpAutoloadCommand.php
Labels: Feature

#12120 Show warnings for each missing platform package in create-project
  src/Composer/Package/Version/VersionSelector.php
Labels: Feature

#12115 Validate licenses passed into init command
  src/Composer/Command/InitCommand.php
  tests/Composer/Test/Command/InitCommandTest.php
Labels: Feature

#12114 Add ability to reinstall packages by type
  src/Composer/Command/CompletionTrait.php
  src/Composer/Command/ReinstallCommand.php
  tests/Composer/Test/Command/ReinstallCommandTest.php
Labels: Feature

#12121 Fix type of $learnedLiterals to avoid issues
  composer.lock
  phpstan/baseline.neon
  src/Composer/Command/ShowCommand.php
  src/Composer/DependencyResolver/Decisions.php
  src/Composer/DependencyResolver/DefaultPolicy.php
  src/Composer/DependencyResolver/GenericRule.php
  src/Composer/DependencyResolver/MultiConflictRule.php
  src/Composer/DependencyResolver/PolicyInterface.php
  src/Composer/DependencyResolver/PoolBuilder.php
  src/Composer/DependencyResolver/PoolOptimizer.php
  src/Composer/DependencyResolver/Problem.php
  src/Composer/DependencyResolver/Request.php
  src/Composer/DependencyResolver/Rule.php
  src/Composer/DependencyResolver/Rule2Literals.php
  src/Composer/DependencyResolver/RuleSet.php
  src/Composer/DependencyResolver/RuleSetGenerator.php
  src/Composer/DependencyResolver/RuleSetIterator.php
  src/Composer/DependencyResolver/Solver.php
  src/Composer/DependencyResolver/SolverProblemsException.php
  src/Composer/DependencyResolver/Transaction.php
  tests/Composer/Test/DependencyResolver/DefaultPolicyTest.php
Labels: Refactoring

#12122 Add --patch-only flag to update command to restrict updates to patch versions and make them safer
  doc/03-cli.md
  src/Composer/Command/UpdateCommand.php
  tests/Composer/Test/Command/UpdateCommandTest.php
Labels: Feature

#12129 Make version guessing more deterministic if two branches appear to be the base of a feature branch
  src/Composer/Package/Version/VersionGuesser.php
Labels: Bug

#12123 JSON schema updates
  res/composer-lock-schema.json
  res/composer-repository-schema.json
  res/composer-schema.json
  src/Composer/Command/DiagnoseCommand.php
  src/Composer/Json/JsonFile.php
  src/Composer/Package/Locker.php
Labels: Feature
