Repository composer/composer, pull requests merged in 2024-02, with the labels that each got.

#11813 Update plugin documentation
  doc/articles/plugins.md
Labels: Documentation

#11829 Add detection of constraints which do not match anything in validate command
  src/Composer/Package/Loader/ValidatingArrayLoader.php
  tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
Labels: Feature

#11812 issue #11811 auth token links on separate lines
  src/Composer/Util/Bitbucket.php
  src/Composer/Util/GitHub.php
  src/Composer/Util/GitLab.php
Labels: Feature

#11688 Diagnose command: Add GitHub OAuth token expiration date information
  src/Composer/Command/DiagnoseCommand.php
Labels: Feature

#11842 Output more warnings about plugins being disabled to hint that it may cause problems
  src/Composer/Console/Application.php
  src/Composer/Installer/InstallationManager.php
  src/Composer/Installer/PluginInstaller.php
  src/Composer/Plugin/PluginManager.php
Labels: Bug

#11816 Add tests for SelfUpdateCommand
  .gitignore
  tests/Composer/Test/AllFunctionalTest.php
  tests/Composer/Test/Command/SelfUpdateCommandTest.php
Labels: Needs Work
