Repository composer/composer, pull requests merged in 2024-04, with the labels that each got.

#11905 Update keywords documentation
  doc/04-schema.md
Labels: Documentation

#11922 chore: remove repetitive words
  CHANGELOG.md
  UPGRADE-2.0.md
Labels: Documentation

#11915 Refactor proxy handling to require https_proxy
  phpstan/baseline.neon
  src/Composer/Console/Application.php
  src/Composer/Util/Http/CurlDownloader.php
  src/Composer/Util/Http/ProxyHelper.php
  src/Composer/Util/Http/ProxyItem.php
  src/Composer/Util/Http/ProxyManager.php
  src/Composer/Util/Http/RequestProxy.php
  src/Composer/Util/RemoteFilesystem.php
  src/Composer/Util/StreamContextFactory.php
  tests/Composer/Test/Util/Http/ProxyHelperTest.php
  tests/Composer/Test/Util/Http/ProxyItemTest.php
  tests/Composer/Test/Util/Http/ProxyManagerTest.php
  tests/Composer/Test/Util/Http/RequestProxyTest.php
Labels: Bug, Refactoring

#11955 Fix Composer autoloader being hijackable by script/plugin event handlers
  phpstan/baseline-8.1.neon
  phpstan/baseline.neon
  src/Composer/EventDispatcher/EventDispatcher.php
Labels: Bug
