Repository composer/composer, pull requests merged in 2024-10, with the labels that each got.

#12139 Handle dump-autoload where vendor folder is not installed or not complete
  src/Composer/Command/DumpAutoloadCommand.php
Labels: Feature

#12143 Add version information to Controlling additional arguments doc
  doc/articles/scripts.md
Labels: Documentation

#12148 Fix --strict-ambiguous to really report all issues
  composer.json
  composer.lock
  src/Composer/Autoload/AutoloadGenerator.php
  src/Composer/Command/DumpAutoloadCommand.php
Labels: Bug

#12146 Fix create-project to reuse the target folders permissions for files created
  src/Composer/Command/CreateProjectCommand.php
  src/Composer/Config.php
  src/Composer/Repository/RepositoryFactory.php
Labels: Bug

#12149 Clean up lock update code to remove redundancy and avoid errors
  src/Composer/Command/BumpCommand.php
  src/Composer/Command/RequireCommand.php
  src/Composer/Package/Locker.php
Labels: Refactoring

#12176 Fix handling of signals in non-PHP binaries run via proxies
  src/Composer/Installer/BinaryInstaller.php
Labels: Bug

#12179 Add hint how ambiguous class issues can be resolved, refs #6221
  src/Composer/Autoload/AutoloadGenerator.php
Labels: Documentation

#12178 Warn/throw when we detect git safe.directory errors
  src/Composer/Command/StatusCommand.php
  src/Composer/Downloader/PathDownloader.php
  src/Composer/Downloader/VcsDownloader.php
  src/Composer/Factory.php
  src/Composer/Package/Loader/RootPackageLoader.php
  src/Composer/Package/Version/VersionGuesser.php
  src/Composer/Repository/PathRepository.php
  src/Composer/Repository/Vcs/GitDriver.php
  src/Composer/Util/Git.php
Labels: Bug
