Repository composer/composer, pull requests merged in 2025-01, with the labels that each got.

#12261 Make use of Phar::running() to get the current phar path
  src/Composer/Command/SelfUpdateCommand.php
  src/Composer/Util/Tar.php
  tests/Composer/Test/AllFunctionalTest.php
  tests/Composer/Test/Command/SelfUpdateCommandTest.php
Labels: Refactoring

#12263 Fix unstable order of psr-0 and psr-4 rules
  src/Composer/Autoload/AutoloadGenerator.php
Labels: Bug

#12248 Allow redirect responses to output warnings/infos
  src/Composer/Util/Http/CurlDownloader.php
  src/Composer/Util/RemoteFilesystem.php
Labels: Backport-2.2

#12247 Discard unsupported FUNDING.yml URL values
  src/Composer/Repository/Vcs/GitHubDriver.php
  tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Labels: Bug

#12283 Fix command name parsing to take into account global input options
  src/Composer/Console/Application.php
Labels: Bug

#12231 Adding explicit message to `why-not` if package is already installed
  src/Composer/Command/BaseDependencyCommand.php
  tests/Composer/Test/Command/BaseDependencyCommandTest.php
Labels: Bug

#12268 Suppress require-dev hint when requiring things globally
  src/Composer/Command/RequireCommand.php
  src/Composer/Factory.php
  src/Composer/PartialComposer.php
Labels: Bug

#12269 Fix regression from #12233 in InstalledVersions when reload is used
  src/Composer/InstalledVersions.php
  tests/Composer/Test/InstalledVersionsTest.php
  tests/bootstrap.php
Labels: Bug

#12266 Copy source ref to dist ref if a custom dist info is present in non-dist-supporting drivers
  src/Composer/Repository/VcsRepository.php
Labels: Bug, Backport-2.2
